export const styles = {
  adminContainer: {
    maxWidth: '1400px',
    margin: '0 auto',
    padding: '2rem',
    backgroundColor: '#f8fafc',
    minHeight: '100vh',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '2rem',
    paddingBottom: '1rem',
    borderBottom: '1px solid #e2e8f0',
  },
  title: {
    fontSize: '2rem',
    color: '#1e293b',
    fontWeight: '600',
    margin: 0,
  },
  statsContainer: {
    display: 'flex',
    gap: '1rem',
    marginBottom: '2rem',
  },
  statCard: {
    flex: 1,
    backgroundColor: 'white',
    padding: '1.5rem',
    borderRadius: '0.5rem',
    boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
    borderLeft: '4px solid #6366f1',
  },
  statTitle: {
    fontSize: '0.875rem',
    color: '#64748b',
    marginBottom: '0.5rem',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  statValue: {
    fontSize: '1.5rem',
    color: '#1e293b',
    fontWeight: '700',
  },
  loading: {
    textAlign: 'center',
    padding: '3rem',
    color: '#64748b',
    fontSize: '1.125rem',
  },
  messagesGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))',
    gap: '1.5rem',
  },
  messageCard: {
    backgroundColor: 'white',
    border: '1px solid #e2e8f0',
    borderRadius: '0.75rem',
    padding: '1.5rem',
    boxShadow: '0 1px 2px rgba(0,0,0,0.05)',
    transition: 'transform 0.2s, box-shadow 0.2s',
    '&:hover': {
      transform: 'translateY(-2px)',
      boxShadow: '0 4px 6px rgba(0,0,0,0.1)',
    },
  },
  messageHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '1rem',
    gap: '1rem',
  },
  messageMeta: {
    flex: 1,
  },
  messageName: {
    fontSize: '1.125rem',
    color: '#1e293b',
    fontWeight: '600',
    marginBottom: '0.25rem',
  },
  messageEmail: {
    fontSize: '0.875rem',
    color: '#64748b',
    display: 'block',
    marginBottom: '0.5rem',
    wordBreak: 'break-all',
  },
  messageDate: {
    fontSize: '0.75rem',
    color: '#94a3b8',
  },
  messageBody: {
    fontSize: '0.9375rem',
    color: '#334155',
    lineHeight: '1.5',
    marginTop: '1rem',
    paddingTop: '1rem',
    borderTop: '1px solid #f1f5f9',
  },
  deleteButton: {
    background: 'none',
    border: 'none',
    fontSize: '1.25rem',
    cursor: 'pointer',
    color: '#ef4444',
    padding: '0.25rem',
    borderRadius: '50%',
    transition: 'background-color 0.2s',
    '&:hover': {
      backgroundColor: '#fee2e2',
    },
  },
  noMessages: {
    textAlign: 'center',
    color: '#64748b',
    fontSize: '1.125rem',
    padding: '3rem',
    gridColumn: '1 / -1',
    backgroundColor: 'white',
    borderRadius: '0.75rem',
    boxShadow: '0 1px 2px rgba(0,0,0,0.05)',
  },
  filters: {
    display: 'flex',
    gap: '1rem',
    marginBottom: '1.5rem',
    alignItems: 'center',
  },
  filterLabel: {
    fontSize: '0.875rem',
    color: '#64748b',
  },
  filterSelect: {
    padding: '0.5rem 1rem',
    borderRadius: '0.375rem',
    border: '1px solid #e2e8f0',
    backgroundColor: 'white',
    fontSize: '0.875rem',
    color: '#334155',
  },
  homeButton: {
    padding: '0.5rem 1rem',
    backgroundColor: '#2c3e50',
    color: '#fff',
    border: 'none',
    borderRadius: '0.375rem',
    fontSize: '0.875rem',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    '&:hover': {
      backgroundColor: '#4f46e5',
      transform: 'translateY(-1px)',
      boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
    },
    '&:active': {
      transform: 'translateY(0)',
    },
  },
};